language: python
python: "3.8"

before_install:
- pip install poetry

install:
- poetry install

script:
- poetry run pytest --packages-path $TRAVIS_BUILD_DIR/tests/fixtures --config $TRAVIS_BUILD_DIR/data/config.yaml
