os: list()
defaults:
  pm:
    app: include('package-manager')
    backend: include('package-manager')
    font: include('package-manager')
    driver: include('package-manager')
    vscode: include('package-manager')
    provisioned: include('package-manager')
  tags: list()
---
package-manager:
  any: list(required=False)
  windows: list(required=False)
  ubuntu: list(required=False)
  darwin: list(required=False)
